name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [windowns-latest]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
    
    - name: Restore NuGet Packages
      run: nuget restore "Open VTT.sln"
    
    - name: Build the Solution - Debug AnyCPU
      run: msbuild "Open VTT.sln" /property:Configuration=Debug /property:Platform=AnyCPU
    - name: Build the Solution - Release AnyCPU
      run: msbuild "Open VTT.sln" /property:Configuration=Release /property:Platform=AnyCPU
    - name: Build the Solution - Debug X64
      run: msbuild "Open VTT.sln" /property:Configuration=Debug /property:Platform=x64
    - name: Build the Solution - Release x64
      run: msbuild "Open VTT.sln" /property:Configuration=Release /property:Platform=x64
    
