name: CI Build & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2019
    env:
      GH_TOKEN: ${{ github.token }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup GitHub CLI
      uses: sersoft-gmbh/setup-gh-cli-action@v1.0.1
      with:
        version: latest
        github-token: ${{ github.token }}
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Clear & Install NuGet Packages
      run: |
        nuget locals all -clear
        nuget restore "Open VTT.sln"
      
    - name: Build the Client & Server in all formats
      run: |
        msbuild "Open VTT.sln" /property:Configuration=Debug /property:Platform="Any CPU"
        msbuild "Open VTT.sln" /property:Configuration=Release /property:Platform="Any CPU"
        msbuild "Open VTT.sln" /property:Configuration=Debug /property:Platform=x64
        msbuild "Open VTT.sln" /property:Configuration=Release /property:Platform=x64
        
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Debug /property:Platform="Any CPU"
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Release /property:Platform="Any CPU"
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Debug /property:Platform=x64
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Release /property:Platform=x64

    - name: Pack Open VTT Client & Server Artifacts
      run: |
        cd "Open VTT"
        cd bin
        
        tar.exe -a -c -f "Debug Any CPU.zip" Debug
        tar.exe -a -c -f "Release Any CPU.zip" Release
        tar.exe -a -c -f "Debug x64.zip" "Debug x64"
        tar.exe -a -c -f "Release x64.zip" "Release x64"
        
        mkdir Artifacts
        move "Debug Any CPU.zip" Artifacts
        move "Release Any CPU.zip" Artifacts
        move "Debug x64.zip" Artifacts
        move "Release x64.zip" Artifacts
        
        cd ..
        cd ..
        
        cd OpenVTT.Server
        cd bin
        
        tar.exe -a -c -f "Server Debug Any CPU.zip" Debug
        tar.exe -a -c -f "Server Release Any CPU.zip" Release
        tar.exe -a -c -f "Server Debug x64.zip" "Debug x64"
        tar.exe -a -c -f "Server Release x64.zip" "Release x64"
        
        mkdir "Server Artifacts"
        move "Server Debug Any CPU.zip" "Server Artifacts"
        move "Server Release Any CPU.zip" "Server Artifacts"
        move "Server Debug x64.zip" "Server Artifacts"
        move "Server Release x64.zip" "Server Artifacts"

    - name: Create automated Release
      run: |
        gh release create CI_Release -t "CI Release "+{{DateTime.Now}} -n "CI Release with Current Build Artifacts attached."
        gh release upload CI_Release "Open VTT\\bin\\Artifacts\\Debug Any CPU.zip" --clobber
        gh release upload CI_Release "Open VTT\\bin\\Artifacts\\Release Any CPU.zip" --clobber
        gh release upload CI_Release "Open VTT\\bin\\Artifacts\\Debug x64.zip" --clobber
        gh release upload CI_Release "Open VTT\\bin\\Artifacts\\Release x64.zip" --clobber
        
        gh release upload CI_Release "OpenVTT.Server\\bin\\Server Artifacts\\Server Debug Any CPU.zip" --clobber
        gh release upload CI_Release "OpenVTT.Server\\bin\\Server Artifacts\\Server Release Any CPU.zip" --clobber
        gh release upload CI_Release "OpenVTT.Server\\bin\\Server Artifacts\\Server Debug x64.zip" --clobber
        gh release upload CI_Release "OpenVTT.Server\\bin\\Server Artifacts\\Server Release x64.zip" --clobber
