name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup GitHub CLI
      uses: sersoft-gmbh/setup-gh-cli-action@v1.0.1
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Clear NuGet Packages
      run: nuget locals all -clear
    
    - name: Restore NuGet Packages
      run: nuget restore "Open VTT.sln"
      
    - name: Build the Solution in all formats
      run: |
        msbuild "Open VTT.sln" /property:Configuration=Debug /property:Platform="Any CPU"
        msbuild "Open VTT.sln" /property:Configuration=Release /property:Platform="Any CPU"
        msbuild "Open VTT.sln" /property:Configuration=Debug /property:Platform=x64
        msbuild "Open VTT.sln" /property:Configuration=Release /property:Platform=x64
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Debug /property:Platform="Any CPU"
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Release /property:Platform="Any CPU"
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Debug /property:Platform=x64
        msbuild "OpenVTT.Server\OpenVTT.Server.csproj" /property:Configuration=Release /property:Platform=x64

    - name: Pack Open VTT Artifacts
      run: |
        cd "Open VTT"
        cd bin
        tar.exe -a -c -f "Debug Any CPU.zip" Debug
        tar.exe -a -c -f "Release Any CPU.zip" Release
        tar.exe -a -c -f "Debug x64.zip" "Debug x64"
        tar.exe -a -c -f "Release x64.zip" "Release x64"
        mkdir Artifacts
        move "Debug Any CPU.zip" Artifacts
        move "Release Any CPU.zip" Artifacts
        move "Debug x64.zip" Artifacts
        move "Release x64.zip" Artifacts
        
    - name: Pack Open VTT Server Artifacts
      run: |
        cd OpenVTT.Server
        cd bin
        tar.exe -a -c -f "Debug Any CPU.zip" Debug
        tar.exe -a -c -f "Release Any CPU.zip" Release
        tar.exe -a -c -f "Debug x64.zip" "Debug x64"
        tar.exe -a -c -f "Release x64.zip" "Release x64"
        mkdir "Server Artifacts"
        move "Debug Any CPU.zip" "Server Artifacts"
        move "Release Any CPU.zip" "Server Artifacts"
        move "Debug x64.zip" "Server Artifacts"
        move "Release x64.zip" "Server Artifacts"

    - name: Upload Open VTT Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Artifacts
        path: "Open VTT\\bin\\Artifacts"
        
    - name: Upload Open VTT Server Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Server Artifacts"
        path: "OpenVTT.Server\\bin\\Server Artifacts"

    - name: Create automated Release
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/IceUnicorn93/Open-VTT/releases \
        -f tag_name='Automated Release' \
        -f target_commitish='master' \
        -f name='CI Release' \
        -f body='CI Release of the latest Build Artifacts' \
        -F draft=false \
        -F prerelease=false \
        -F generate_release_notes=false 
